const $=id=>document.getElementById(id), clean=s=>(s||'').replace(/\s+/g,' ').trim(), norm=s=>clean(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase(), wc=s=>(s||'').trim()?((s.trim().match(/\S+/g)||[]).length):0, yearOk=y=>/^\d{4}$/.test((y||'').trim());
const authors=v=>(v||'').split(';').map(x=>x.trim()).filter(Boolean);
function joinAuthors(a,lang='es',occ='first'){if(!a.length)return'';if(a.length===1)return a[0];const c=lang==='en'?' & ':' y ';if(a.length===2)return a[0]+c+a[1];if(a.length>=6)return a[0]+' et al.';if(a.length>=3&&a.length<=5&&occ==='later')return a[0]+' et al.';return a.slice(0,-1).join(', ')+c+a[a.length-1]}
function show(el,cls,html){el.className=`output ${cls}`;el.innerHTML=html;el.classList.remove('hidden')}
function esc(s){return(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
function lineAlert(t){const n=wc(t);return n>145?`<li class="warn">${n} palabras: podría superar aproximadamente 10 líneas. Verifica en Word.</li>`:`<li class="good">${n} palabras: sin alerta evidente de extensión.</li>`}

qBtn.onclick=()=>{const a=authors(qAuthors.value),y=qYear.value.trim(),p=qPage.value.trim(),t=qText.value.trim(),e=qEmphasis.value;if(!a.length||!yearOk(y)||!p||!t)return show(qOut,'bad','<h4>🔵 FALTA INFORMACIÓN</h4><p>Completa autor(es), año, página y fragmento. No se inventarán datos.</p>');const n=wc(t),au=joinAuthors(a),tx=esc(t);let m,info;if(n<40){m=e==='author'?`${au} (${y}) ... “${tx}” (p. ${p}).`:`“${tx}” (${au}, ${y}, p. ${p}).`;info='Menos de 40 palabras: dentro del párrafo, entre comillas y sin cursiva.'}else{m=e==='author'?`${au} (${y}) introduce la cita:\n\n    ${tx}.\n    (p. ${p})`:`    ${tx}.\n    (${au}, ${y}, p. ${p})`;info='40 palabras o más: bloque con sangría, sin comillas y sin cursiva; el punto antecede a los datos.'}show(qOut,'ok',`<h4>🟢 Formato orientativo</h4><p><b>${n} palabras.</b> ${info}</p><pre>${m}</pre><p class="small">Verifica fidelidad del fragmento y página real.</p>`)};

function pPrompt(){const a=authors(pAuthors.value),y=pYear.value.trim(),s=pSource.value.trim(),d=pData.value.trim();if(!a.length||!yearOk(y)||!s||!d)return null;const au=joinAuthors(a);return `ACTÚA COMO COPILOTO ACADÉMICO PARA PARAFRASEO SEGÚN APA 6.\n\nTEXTO ORIGINAL:\n${s}\n\nFUENTE REAL PROPORCIONADA:\n${d}\n\nAUTOR(ES): ${au}\nAÑO: ${y}\n\nINSTRUCCIONES:\n1. No inventes autor, año, página, DOI, URL ni datos bibliográficos.\n2. Conserva el significado.\n3. No hagas simple sustitución por sinónimos: reestructura la idea.\n4. Entrega DOS modelos: A) basado en el autor: ${au} (${y})...; B) basado en el texto: ... (${au}, ${y}).\n5. Usa redacción científica e impersonal.\n6. Explica brevemente qué cambiaste para evitar una paráfrasis literal.\n7. Si la fuente carece de datos verificables, indícalo y no inventes nada.`}
pBtn.onclick=()=>{if(!pConfirmed.checked)return show(pOut,'warn','<h4>🟡 Fuente no confirmada</h4><p>Confirma que consultaste la fuente real.</p>');const pr=pPrompt();if(!pr)return show(pOut,'bad','<h4>🔵 FALTA INFORMACIÓN</h4><p>Completa autor(es), año, texto original y datos de fuente.</p>');const au=joinAuthors(authors(pAuthors.value)),y=pYear.value.trim();show(pOut,'ok',`<h4>🟢 Dos modelos a producir</h4><p><b>Modelo A:</b> ${au} (${y}) [paráfrasis con palabras propias].</p><p><b>Modelo B:</b> [Paráfrasis con palabras propias] (${au}, ${y}).</p><p class="small">Copia la solicitud para que ChatGPT redacte ambos a partir del texto real.</p>`)};
pCopy.onclick=async()=>{const pr=pPrompt();if(!pr||!pConfirmed.checked)return alert('Completa los datos y confirma la fuente.');await navigator.clipboard.writeText(pr);alert('Solicitud copiada.')};

aBtn.onclick=()=>{const a=authors(aList.value),y=aYear.value.trim();if(!a.length||!yearOk(y))return show(aOut,'bad','<h4>🔵 FALTA INFORMACIÓN</h4><p>Ingresa apellidos y año válido.</p>');const au=joinAuthors(a,aLang.value,aOccurrence.value);show(aOut,'ok',`<h4>🟢 Formas orientativas</h4><p><b>Autor:</b> ${au} (${y}) ...</p><p><b>Texto:</b> ... (${au}, ${y}).</p><p class="small">Autores ingresados: ${a.length}.</p>`)};

const defs={
book:[['authors','Autor(es)','Apellido, A. A.','full'],['year','Año','2006',''],['title','Título','', 'full'],['city','Ciudad, País','', ''],['publisher','Editorial','', '']],
ebook:[['authors','Autor(es)','','full'],['year','Año','',''],['title','Título','','full'],['url','URL o DOI real','','full']],
chapter:[['authors','Autor(es) del capítulo','','full'],['year','Año','',''],['chapter','Título del capítulo','','full'],['editor','Editor del libro','',''],['book','Título del libro','','full'],['pages','Páginas','53-62',''],['city','Ciudad, País','',''],['publisher','Editorial','','']],
journal:[['authors','Autor(es)','','full'],['year','Año','',''],['article','Título del artículo','','full'],['journal','Revista','','full'],['volume','Volumen','',''],['number','Número','',''],['pages','Páginas','','']],
journalDoi:[['authors','Autor(es)','','full'],['year','Año','',''],['article','Título del artículo','','full'],['journal','Revista','','full'],['volume','Volumen','',''],['number','Número','',''],['pages','Páginas','',''],['doi','DOI real','','full']],
journalOnline:[['authors','Autor(es)','','full'],['year','Año','',''],['article','Título del artículo','','full'],['journal','Revista','','full'],['volume','Volumen','',''],['number','Número','',''],['pages','Páginas','',''],['url','URL real','','full']],
thesis:[['authors','Autor(es)','','full'],['year','Año','',''],['title','Título','','full'],['degree','Tipo de trabajo','tesis de pregrado',''],['institution','Institución','','full'],['place','Lugar','','']],
report:[['organization','Organización autora','','full'],['year','Año','',''],['title','Título del informe','','full'],['publication','Número de publicación (si existe)','',''],['url','URL real','','full']],
web:[['authors','Autor o entidad','','full'],['date','Fecha','2024 / 5 de mayo de 2024',''],['title','Título de la página','','full'],['publisher','Casa publicadora / sitio','','full'],['url','URL real','','full']],
conference:[['authors','Autor(es)','','full'],['date','Fecha','',''],['title','Título de la ponencia','','full'],['president','Responsable del evento','',''],['event','Nombre del evento','','full'],['organization','Organización','','full'],['place','Lugar','','']]
};
function renderFields(){rFields.innerHTML=defs[rType.value].map(([id,l,ph,cl])=>`<div class="${cl}"><label>${l}</label><input data-ref="${id}" placeholder="${ph}"></div>`).join('')}renderFields();rType.onchange=renderFields;
function rd(){const d={};document.querySelectorAll('[data-ref]').forEach(x=>d[x.dataset.ref]=x.value.trim());return d}
function required(type,d){const optional=new Set(['publication','number','pages']);return defs[type].filter(x=>!optional.has(x[0])).every(x=>d[x[0]])}
function buildRef(t,d){switch(t){case'book':return`${d.authors} (${d.year}). ${d.title}. ${d.city}: ${d.publisher}.`;case'ebook':return/^10\./.test(d.url)?`${d.authors} (${d.year}). ${d.title}. doi: ${d.url}`:`${d.authors} (${d.year}). ${d.title}. Recuperado de ${d.url}`;case'chapter':return`${d.authors} (${d.year}). ${d.chapter}. En ${d.editor} (Ed.), ${d.book} (pp. ${d.pages}). ${d.city}: ${d.publisher}.`;case'journal':return`${d.authors} (${d.year}). ${d.article}. ${d.journal}, ${d.volume}${d.number?`(${d.number})`:''}, ${d.pages}.`;case'journalDoi':return`${d.authors} (${d.year}). ${d.article}. ${d.journal}, ${d.volume}${d.number?`(${d.number})`:''}, ${d.pages}. doi: ${d.doi}`;case'journalOnline':return`${d.authors} (${d.year}). ${d.article}. ${d.journal}, ${d.volume}${d.number?`(${d.number})`:''}, ${d.pages}. Recuperado de ${d.url}`;case'thesis':return`${d.authors} (${d.year}). ${d.title} (${d.degree}). ${d.institution}, ${d.place}.`;case'report':return`${d.organization} (${d.year}). ${d.title}${d.publication?` (${d.publication})`:''}. Recuperado de ${d.url}`;case'web':return`${d.authors} (${d.date}). ${d.title}. ${d.publisher}. Recuperado de ${d.url}`;case'conference':return`${d.authors} (${d.date}). ${d.title}. En ${d.president} (Presidencia), ${d.event}. Evento llevado a cabo por ${d.organization}, ${d.place}.`}}
rBtn.onclick=()=>{const t=rType.value,d=rd();if(!rConfirmed.checked)return show(rOut,'warn','<h4>🟡 Fuente no confirmada</h4><p>Confirma que los datos provienen de la fuente real.</p>');if(!required(t,d))return show(rOut,'bad','<h4>🔵 FALTA INFORMACIÓN</h4><p>Completa los campos necesarios. No se inventarán datos.</p>');show(rOut,'ok',`<h4>🟢 Referencia orientativa APA 6</h4><p>${buildRef(t,d)}</p><p class="small">Aplica sangría francesa en Word y verifica todos los datos con la fuente original.</p>`)};

revBtn.onclick=()=>{const t=revText.value.trim(),type=revType.value,a=revAuthor.value.trim(),y=revYear.value.trim();if(!t)return show(revOut,'bad','<h4>🔵 FALTA INFORMACIÓN</h4><p>Pega el párrafo completo.</p>');const ck=[],ha=a?norm(t).includes(norm(a)):false,hy=yearOk(y)?t.includes(y):false,hp=/\bp{1,2}\.\s*\d+/i.test(t),hq=/[“"][^”"]+[”"]/.test(t),fp=/\b(yo|nosotros|nosotras|mi|mis|nuestro|nuestra)\b/i.test(t);ck.push(a?(ha?`<li class="good">Se detecta ${a}.</li>`:`<li class="badtext">No se detecta ${a}.</li>`):'<li class="warn">No indicaste apellido esperado.</li>');ck.push(yearOk(y)?(hy?`<li class="good">Se detecta ${y}.</li>`:`<li class="badtext">No se detecta ${y}.</li>`):'<li class="warn">No indicaste año válido.</li>');if(type==='direct'){ck.push(hp?'<li class="good">Se detecta página.</li>':'<li class="badtext">La cita textual requiere página.</li>');ck.push(hq?'<li class="good">Se detectan comillas; coherente si la cita es menor de 40 palabras.</li>':'<li class="warn">No se detectan comillas; solo sería correcto para bloque de 40+ palabras.</li>')}else ck.push('<li class="good">En parafraseo, la guía exige autor y año.</li>');ck.push(fp?'<li class="warn">Se detecta primera persona.</li>':'<li class="good">No se detecta primera persona.</li>');ck.push(lineAlert(t));const bad=(ck.join('').match(/badtext/g)||[]).length,warn=(ck.join('').match(/class="warn"/g)||[]).length;show(revOut,bad?'bad':warn?'warn':'ok',`<h4>${bad?'🔴 REQUIERE CORRECCIÓN':warn?'🟡 REVISAR':'🟢 CUMPLE FORMALMENTE'}</h4><ul>${ck.join('')}</ul><p class="small">Esta revisión formal no prueba por sí sola que la fuente exista ni que el contenido sea fiel al original.</p>`)};

function audit(){return`ACTÚA COMO COPILOTO ACADÉMICO ESPECIALIZADO EN APA 6 PARA PROYECTO DE GRADO.\n\nREGLAS:\n1. No inventes autores, años, páginas, DOI, URL, editoriales, títulos ni fuentes.\n2. Si falta un dato, indica FALTA INFORMACIÓN.\n3. Menos de 40 palabras: cita textual integrada, comillas, autor-año-página.\n4. 40 o más: bloque con sangría, sin comillas ni cursiva; punto antes de los datos.\n5. Paráfrasis: idea fiel con palabras propias; autor y año.\n6. 3-5 autores: primera vez todos, luego primero + et al.; 6+ desde la primera.\n7. Toda cita debe corresponder con la referencia final.\n8. No hagas el trabajo por el estudiante: orienta y explica.\n9. Revisa si el párrafo podría superar aproximadamente 10 líneas y sugiere comprobarlo en Word.\n\nPÁRRAFO:\n${revText.value.trim()||'[NO INGRESADO]'}\n\nTIPO DE CITA: ${revType.value}\nAUTOR ESPERADO: ${revAuthor.value.trim()||'[NO INDICADO]'}\nAÑO: ${revYear.value.trim()||'[NO INDICADO]'}\n\nTEXTO ORIGINAL PARA PARAFRASEO:\n${pSource.value.trim()||'[NO INGRESADO]'}\n\nDATOS REALES DE LA FUENTE:\n${pData.value.trim()||'[NO INGRESADOS]'}\n\nRESPONDE CON: A) tipo de cita; B) qué está bien; C) qué falta; D) cómo corregirlo sin inventar; E) si se pidió parafraseo, dos modelos (autor/texto); F) control de extensión; G) referencia solo con datos reales.`}
auditBtn.onclick=async()=>{await navigator.clipboard.writeText(audit());auditStatus.textContent='Prompt de auditoría APA 6 copiado.'};
